### ISSUE TITLE
Error with odk2openVA version 1.4.1

### ISSUE THREAD

**Issue by jfiksel** [verbal-autopsy-software/CrossVA#1]
When I run the following code

```
library(CrossVA)
record_f_name <- system.file("sample", "who151_va_output.csv", package = "CrossVA")
records <- read.csv(record_f_name)
output2 <- odk2openVA(records, version = "1.4.1")
```

I get the error `Error in .subset(x, j) : invalid subscript type 'list'`

It would be great to get this fixed soon. Thanks!

**Comment by jarathomas** [comment]
With example file who151_va_output.csv, please use the odk2openVA function with argument version = "1.5.1".

The example file who_va_output.csv can be used with argument version = "1.4.1".

**Comment by jfiksel** [comment]
Great thanks!
