### ISSUE TITLE
no odk2openVA method in the new CrossVA package

### ISSUE THREAD

**Issue by QollinsOchieng** [verbal-autopsy-software/CrossVA#3]
After installing the new CrossVA , I cannot find the method odk2openVA?

**Comment by jarathomas** [comment]
Can you provide a little more information?  When you run the following commands, do you not see a help file?

library(CrossVA)
?odk2openVA

**Comment by QollinsOchieng** [comment]
Yes, when I run that there is no help file especially for the new release of CrossVA. It outputs no package is found error
also in the new Shiny R code, it references map_records2 method which also does not exist.

Regards,Odhiambo Collins Ochieng
KEMRI-KISUMU
Tel: +254702344393
Email: coodhiambo@kemricdc.org or qollinsochieng@gmail.com
-------- Original message --------From: Jason Thomas <notifications@github.com> Date: 02/04/2019  21:37  (GMT+03:00) To: verbal-autopsy-software/CrossVA <CrossVA@noreply.github.com> Cc: QollinsOchieng <qollinsochieng@gmail.com>, Author <author@noreply.github.com> Subject: Re: [verbal-autopsy-software/CrossVA] no odk2openVA method in the new CrossVA package (#3) 
Can you provide a little more information?  When you run the following commands, do you not see a help file?
library(CrossVA)

?odk2openVA

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/verbal-autopsy-software/CrossVA","title":"verbal-autopsy-software/CrossVA","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/verbal-autopsy-software/CrossVA"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jarathomas in #3: Can you provide a little more information?  When you run the following commands, do you not see a help file?\r\n\r\nlibrary(CrossVA)\r\n?odk2openVA"}],"action":{"name":"View Issue","url":"https://github.com/verbal-autopsy-software/CrossVA/issues/3#issuecomment-479139204"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/verbal-autopsy-software/CrossVA/issues/3#issuecomment-479139204",
"url": "https://github.com/verbal-autopsy-software/CrossVA/issues/3#issuecomment-479139204",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jarathomas** [comment]
OK, I pushed a new version of the shiny app, which should be able to handle different versions of CrossVA.  But it sounds like there was a problem with the installation of the CrossVA package.  In R, run the command  `.libPaths()` and then check those folders for CrossVA.  If you do find a package for the folder, try  `library("CrossVA", lib.loc = "/Path/to/package")`  ; otherwise, try to reinstall the package and keep an eye out for any errors.  Let me know if it looks like the installation was successful and you are still running into errors.
