### ISSUE TITLE
Bug in odk2openva_v151.R re: survey question #284

### ISSUE THREAD

**Issue by mbrudd** [verbal-autopsy-software/CrossVA#4]
When mapping results for question #284 to interVA format in lines 977-980,

nMonths[is.na(nMonths) & !is.na(nDays)] <- 0
nDays[is.na(nDays) & !is.na(nMonths)] <- 0
iv5Out[nMonths + nDays/30.4 <=12, 284] <- "y"
iv5Out[nMonths + nDays/30.4 > 12, 284] <- "n"

there's a bug if nMonths and nDays both consist entirely of NA's -- I have a VA dataset for which this is the case! I modified my own local version of odk2openva_v151.R as follows:

nMonths[is.na(nMonths) & !is.na(nDays)] <- 0
nDays[is.na(nDays) & !is.na(nMonths)] <- 0
indexData <- which( is.numeric(nMonths) & is.numeric(nDays) )
if( length(indexData) > 0 ){
    iv5Out[ indexData, 284] <- ifelse( nMonths[indexData] + (nDays[indexData]/30.4) <=12, "y", "n")
}

Happy to submit a pull request or to have this fixed by a maintainer. Thanks!

**Comment by jarathomas** [comment]
Thanks for letting us know!  I've added the following to the latest commit for odk2openva_v151.R:

```
    nMonths <- odk[ , indexDataM]
    nDays   <- odk[ , indexDataD]
    nMonths[is.na(odk[ , indexDataM]) & !is.na(odk[ , indexDataD])] <- 0
    nDays[is.na(odk[ , indexDataD]) & !is.na(odk[ , indexDataM])] <- 0
    naMonthsAndDays <- is.na(odk[ , indexDataM]) & is.na(odk[ , indexDataD])
    iv5Out[nMonths + nDays/30.4 <=12 & !naMonthsAndDays, 284] <- "y"
    iv5Out[nMonths + nDays/30.4 > 12 & !naMonthsAndDays, 284] <- "n"
```
There were a couple bug fixes for some of the other indicators. Please let us know if you find any other issues.

**Comment by mbrudd** [comment]
Thanks for working on this! I would like to make one additional suggestion: in the last 2 lines, checking naMonthsAndDays should  happen first, before evaluating the condition nMonths + nDays/30.4 <=12 . That way, the calculation will only be performed if !naMonthsAndDays is true; in the current order, the calculation will be done first and will throw an error if !naMonthsAndDays is false.

**Comment by jarathomas** [comment]
Ugh, I knew I should have waited before submitting to CRAN.  Thanks, yet again, for the help!  I've added your fix (of checking NA of naMonthsAndDays first) with the most recent commit (v1.0.1), and will send along to CRAN after another week or so.

**Comment by mbrudd** [comment]
No worries -- we're all in this together! :)
